# Configuración principal de GitHub Pages
# _config.yml

title: "Simulador Predictivo de Impacto Financiero"
description: "Herramienta avanzada para evaluación del impacto económico de decisiones estratégicas empresariales"
url: "https://tu-usuario.github.io"
baseurl: "/simulador-impacto-financiero"

# Información del autor y proyecto
author:
  name: "Equipo de Análisis Financiero"
  email: "contacto@ejemplo.com"
  github: "tu-usuario"
  linkedin: "tu-perfil-linkedin"

# Configuración del repositorio
repository: "tu-usuario/simulador-impacto-financiero"
github_username: "tu-usuario"

# Configuración de Jekyll
markdown: kramdown
highlighter: rouge
theme: minima

# Configuración de kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Plugins de Jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-gist

# Configuración de SEO
seo:
  name: "Simulador Predictivo de Impacto Financiero"
  type: "SoftwareApplication"
  author: "Equipo de Análisis Financiero"
  description: "Herramienta de modelado financiero para evaluación de decisiones estratégicas con análisis de riesgo y simulación de escenarios"

# Configuración de navegación
navigation:
  - title: "Inicio"
    url: "/"
  - title: "Simulador"
    url: "/simulator/"
  - title: "Documentación"
    url: "/docs/"
  - title: "Ejemplos"
    url: "/examples/"
  - title: "API"
    url: "/api/"
  - title: "GitHub"
    url: "https://github.com/tu-usuario/simulador-impacto-financiero"

# Configuración de colecciones
collections:
  examples:
    output: true
    permalink: /:collection/:name/
  tutorials:
    output: true
    permalink: /:collection/:name/
  api_docs:
    output: true
    permalink: /:collection/:name/

# Configuración de defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Equipo de Análisis Financiero"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "example"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"

# Configuración de exclusiones
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tests/
  - .pytest_cache/
  - __pycache__/
  - .github/
  - README.md
  - requirements.txt

# Configuración de inclusiones específicas
include:
  - _pages
  - assets

# Configuración de paginación
paginate: 10
paginate_path: "/blog/page:num/"

# Configuración de permalinks
permalink: /:categories/:year/:month/:day/:title/

# Variables personalizadas para el sitio
project:
  version: "1.0.0"
  status: "Active Development"
  license: "MIT"
  language: "Python"
  started: "2025"
  
features:
  - "Modelado Financiero Avanzado"
  - "Análisis de Sensibilidad"
  - "Simulación Monte Carlo"
  - "Visualización Interactiva"
  - "Generación de Reportes"
  - "API REST"

technologies:
  backend:
    - "Python 3.8+"
    - "NumPy"
    - "Pandas"
    - "SciPy"
  frontend:
    - "HTML5"
    - "CSS3"
    - "JavaScript ES6+"
    - "Bootstrap 5"
  visualization:
    - "Matplotlib"
    - "Plotly"
    - "Chart.js"
  testing:
    - "PyTest"
    - "Coverage.py"
  deployment:
    - "GitHub Actions"
    - "GitHub Pages"

# Configuración de Google Analytics (opcional)
google_analytics: ""

# Configuración de comentarios (opcional)
disqus:
  shortname: ""

# Configuración de redes sociales
social:
  links:
    - "https://github.com/tu-usuario"
    - "https://linkedin.com/in/tu-perfil"

---

# Layout personalizado para páginas principales
# _layouts/default.html

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if page.title %}{{ page.title }} | {% endif %}{{ site.title }}</title>
    <meta name="description" content="{% if page.description %}{{ page.description }}{% else %}{{ site.description }}{% endif %}">
    
    <!-- SEO Tags -->
    {% seo %}
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    
    <!-- Highlight.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github.min.css">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ '/assets/css/main.css' | relative_url }}">
    
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{{ '/assets/favicon.ico' | relative_url }}">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
        <div class="container">
            <a class="navbar-brand fw-bold" href="{{ '/' | relative_url }}">
                <i class="fas fa-chart-line me-2"></i>{{ site.title }}
            </a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% for item in site.navigation %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ item.url | relative_url }}">{{ item.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <main>
        {{ content }}
    </main>

    <!-- Footer -->
    <footer class="bg-dark text-light py-4 mt-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h5>{{ site.title }}</h5>
                    <p class="mb-0">{{ site.description }}</p>
                </div>
                <div class="col-md-6 text-md-end">
                    <p class="mb-1">Versión {{ site.project.version }}</p>
                    <p class="mb-0">
                        <a href="{{ site.repository }}" class="text-light">
                            <i class="fab fa-github me-1"></i>Ver en GitHub
                        </a>
                    </p>
                </div>
            </div>
            <hr class="my-3">
            <div class="row">
                <div class="col-12 text-center">
                    <p class="mb-0">&copy; {{ site.project.started }}-{{ 'now' | date: '%Y' }} {{ site.author.name }}. Licencia {{ site.project.license }}.</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- Highlight.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/python.min.js"></script>
    <script>hljs.highlightAll();</script>
    
    <!-- Custom JavaScript -->
    <script src="{{ '/assets/js/main.js' | relative_url }}"></script>
    
    <!-- Analytics (si está configurado) -->
    {% if site.google_analytics %}
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ site.google_analytics }}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '{{ site.google_analytics }}');
    </script>
    {% endif %}
</body>
</html>

---

# CSS personalizado para el sitio
# assets/css/main.css

:root {
  --primary-color: #0d6efd;
  --secondary-color: #6c757d;
  --success-color: #198754;
  --warning-color: #ffc107;
  --danger-color: #dc3545;
  --info-color: #0dcaf0;
  --light-color: #f8f9fa;
  --dark-color: #212529;
}

/* Estilos generales */
body {
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  line-height: 1.6;
}

/* Navegación */
.navbar-brand {
  font-size: 1.5rem;
}

/* Hero section */
.hero-section {
  background: linear-gradient(135deg, var(--primary-color), #4dabf7);
  color: white;
  padding: 4rem 0;
}

/* Cards */
.card {
  transition: transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out;
  border: none;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(0,0,0,0.15);
}

/* Code blocks */
.highlight {
  border-radius: 8px;
  padding: 1rem;
  margin: 1rem 0;
  background-color: #f8f9fa;
}

/* Botones personalizados */
.btn-primary {
  background-color: var(--primary-color);
  border-color: var(--primary-color);
}

.btn-primary:hover {
  background-color: #0b5ed7;
  border-color: #0a58ca;
}

/* Responsividad */
@media (max-width: 768px) {
  .hero-section {
    padding: 2rem 0;
  }
  
  .hero-section h1 {
    font-size: 2rem;
  }
}

/* Estilos para documentación */
.documentation-nav {
  position: sticky;
  top: 100px;
  max-height: calc(100vh - 120px);
  overflow-y: auto;
}

.documentation-content {
  padding-left: 2rem;
}

/* Estilos para ejemplos */
.example-card {
  border-left: 4px solid var(--primary-color);
}

.example-output {
  background-color: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 4px;
  padding: 1rem;
  font-family: 'Courier New', monospace;
}

/* Footer */
footer {
  margin-top: auto;
}

---

# JavaScript personalizado
# assets/js/main.js

// Funciones para la interface del simulador
document.addEventListener('DOMContentLoaded', function() {
    // Inicializar tooltips de Bootstrap
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl);
    });

    // Scroll suave para anclas
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });

    // Copiar código al clipboard
    document.querySelectorAll('.highlight').forEach(block => {
        const button = document.createElement('button');
        button.className = 'btn btn-sm btn-outline-secondary copy-btn';
        button.innerHTML = '<i class="fas fa-copy"></i>';
        button.style.position = 'absolute';
        button.style.top = '10px';
        button.style.right = '10px';
        
        block.style.position = 'relative';
        block.appendChild(button);
        
        button.addEventListener('click', () => {
            const code = block.querySelector('code').innerText;
            navigator.clipboard.writeText(code).then(() => {
                button.innerHTML = '<i class="fas fa-check"></i>';
                setTimeout(() => {
                    button.innerHTML = '<i class="fas fa-copy"></i>';
                }, 2000);
            });
        });
    });
});

// Función para iniciar simulación (placeholder)
function startSimulation() {
    alert('Simulación iniciada. Esta funcionalidad será implementada en la interface web completa.');
}

// Función para ver documentación
function viewDocumentation() {
    window.location.href = './docs/';
}

---

# Página principal del sitio
# index.md

---
layout: default
title: "Inicio"
description: "Simulador Predictivo de Impacto Financiero para evaluación de decisiones estratégicas empresariales"
---

<section class="hero-section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <h1 class="display-4 fw-bold mb-4">Simulador Predictivo de Impacto Financiero</h1>
                <p class="lead mb-4">Evalúe el impacto económico de decisiones estratégicas mediante modelos financieros avanzados, análisis de sensibilidad y simulación de escenarios.</p>
                <div class="d-flex gap-3">
                    <a href="./simulator/" class="btn btn-light btn-lg">
                        <i class="fas fa-play me-2"></i>Iniciar Simulación
                    </a>
                    <a href="./docs/" class="btn btn-outline-light btn-lg">
                        <i class="fas fa-book me-2"></i>Documentación
                    </a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="text-center">
                    <i class="fas fa-chart-line" style="font-size: 8rem; opacity: 0.3;"></i>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto text-center mb-5">
                <h2 class="h1 mb-3">Características Principales</h2>
                <p class="lead text-muted">Herramientas avanzadas para análisis financiero profesional</p>
            </div>
        </div>
        
        <div class="row g-4">
            {% for feature in site.features %}
            <div class="col-md-6 col-lg-4">
                <div class="card h-100 text-center">
                    <div class="card-body">
                        <div class="mb-3">
                            {% case feature %}
                                {% when 'Modelado Financiero Avanzado' %}
                                    <i class="fas fa-calculator fa-2x text-primary"></i>
                                {% when 'Análisis de Sensibilidad' %}
                                    <i class="fas fa-search-dollar fa-2x text-success"></i>
                                {% when 'Simulación Monte Carlo' %}
                                    <i class="fas fa-random fa-2x text-info"></i>
                                {% when 'Visualización Interactiva' %}
                                    <i class="fas fa-chart-bar fa-2x text-warning"></i>
                                {% when 'Generación de Reportes' %}
                                    <i class="fas fa-file-pdf fa-2x text-danger"></i>
                                {% else %}
                                    <i class="fas fa-cog fa-2x text-secondary"></i>
                            {% endcase %}
                        </div>
                        <h5 class="card-title">{{ feature }}</h5>
                        <p class="card-text text-muted">
                            {% case feature %}
                                {% when 'Modelado Financiero Avanzado' %}
                                    Cálculo preciso de VPN, TIR, y métricas financieras estándar
                                {% when 'Análisis de Sensibilidad' %}
                                    Evaluación del impacto de cambios en variables críticas
                                {% when 'Simulación Monte Carlo' %}
                                    Análisis probabilístico para gestión de incertidumbre
                                {% when 'Visualización Interactiva' %}
                                    Gráficos dinámicos y dashboards profesionales
                                {% when 'Generación de Reportes' %}
                                    Reportes ejecutivos automatizados en múltiples formatos
                                {% else %}
                                    Funcionalidad avanzada para análisis financiero
                            {% endcase %}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<section class="py-5 bg-light">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <h2 class="h1 mb-4">Tecnología Moderna</h2>
                <p class="mb-4">Construido con las mejores prácticas de desarrollo y tecnologías líderes en la industria para garantizar precisión, rendimiento y escalabilidad.</p>
                <div class="row g-3">
                    <div class="col-6">
                        <div class="d-flex align-items-center">
                            <i class="fab fa-python fa-2x text-primary me-3"></i>
                            <div>
                                <strong>Python 3.8+</strong><br>
                                <small class="text-muted">Backend robusto</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="d-flex align-items-center">
                            <i class="fas fa-chart-area fa-2x text-success me-3"></i>
                            <div>
                                <strong>NumPy & Pandas</strong><br>
                                <small class="text-muted">Análisis de datos</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Ejemplo de Uso</h5>
                        <pre><code class="language-python">
from core.financial_model import FinancialModel

# Inicializar modelo
model = FinancialModel()

# Cargar escenario
model.load_base_scenario("expansion.json")

# Ejecutar simulación
results = model.run_simulation()

# Mostrar resultados
print(f"VPN: ${results.npv:,.2f}")
print(f"TIR: {results.irr:.2%}")
                        </code></pre>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>